//! Network namespace lifecycle and entry.
//!
//! Two different mechanisms are used here on purpose:
//!
//!   * Namespace *setup* shells out to `ip`. It is a declarative one-shot, the
//!     commands are inspectable, and getting it wrong is loud rather than
//!     subtle.
//!   * Namespace *entry* uses `setns(2)` directly, because correctness there
//!     depends on which thread makes the call - and that is precisely the thing
//!     a shell-out cannot express.

use anyhow::{bail, Context, Result};
use nix::sched::{setns, CloneFlags};
use std::fs;
use std::os::fd::AsFd;
use std::path::Path;
use std::process::Command;

use crate::config::*;

fn ip(args: &[&str]) -> Result<()> {
    let out = Command::new("ip")
        .args(args)
        .output()
        .with_context(|| format!("running `ip {}`", args.join(" ")))?;
    if !out.status.success() {
        bail!(
            "`ip {}` failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(())
}

/// Does the namespace exist? The kernel is the source of truth for tort's
/// state, so there is no state file to go stale or to be left behind by a
/// crash - and no possibility of the connect and disconnect processes
/// disagreeing about whether we are up.
pub fn exists() -> bool {
    Path::new(&format!("/var/run/netns/{NETNS}")).exists()
}

/// Create the namespace, the veth pair, and the addressing.
///
/// Note what is absent: any IPv6 configuration. The namespace is given no IPv6
/// address and no IPv6 route, so IPv6 leaks are not prevented by a rule that
/// might fail - they are impossible, because there is no IPv6 path to leak
/// down. Compare torc, which disabled IPv6 host-wide via sysctl and had to
/// remember to put the user's setting back.
pub fn create() -> Result<()> {
    if exists() {
        bail!("network namespace '{NETNS}' already exists - run `tort down` first");
    }

    ip(&["netns", "add", NETNS])?;

    // Build the veth pair and move one end inside.
    ip(&["link", "add", VETH_HOST, "type", "veth", "peer", "name", VETH_NS])?;
    ip(&["link", "set", VETH_NS, "netns", NETNS])?;

    // Host side.
    ip(&["addr", "add", &format!("{HOST_ADDR}/{SUBNET_LEN}"), "dev", VETH_HOST])?;
    ip(&["link", "set", VETH_HOST, "up"])?;

    // Namespace side: one address, one default route, and nothing else. That
    // single route is the only way out, and it leads to the veth whose peer
    // only ever redirects to tor.
    ip(&["-n", NETNS, "addr", "add", &format!("{NS_ADDR}/{SUBNET_LEN}"), "dev", VETH_NS])?;
    ip(&["-n", NETNS, "link", "set", VETH_NS, "up"])?;
    ip(&["-n", NETNS, "link", "set", "lo", "up"])?;
    ip(&["-n", NETNS, "route", "add", "default", "via", HOST_ADDR])?;

    // net.* sysctls are per-namespace, so this disables IPv6 *inside* the
    // namespace only. The host's IPv6 configuration is not touched at all.
    let _ = Command::new("ip")
        .args(["netns", "exec", NETNS, "sysctl", "-qw", "net.ipv6.conf.all.disable_ipv6=1"])
        .status();

    write_resolv_conf()?;
    Ok(())
}

/// Give the namespace its own resolver.
///
/// `ip netns exec` bind-mounts /etc/netns/<name> over /etc, so a process inside
/// the namespace reads this file as /etc/resolv.conf. The host's real
/// /etc/resolv.conf is never modified, never backed up, and never restored.
fn write_resolv_conf() -> Result<()> {
    fs::create_dir_all(NETNS_ETC).with_context(|| format!("creating {NETNS_ETC}"))?;
    fs::write(
        format!("{NETNS_ETC}/resolv.conf"),
        format!(
            "# Generated by tort.\n\
             # Queries go to the host side of the veth, where nftables redirects\n\
             # UDP/53 to tor's DNSPort ({DNS_PORT}).\n\
             nameserver {HOST_ADDR}\n\
             options edns0\n"
        ),
    )
    .context("writing the namespace resolv.conf")?;
    Ok(())
}

/// Tear the namespace down. Deleting the namespace also destroys the veth pair
/// and every address and route inside it, so this cannot half-succeed the way
/// torc's rule-by-rule teardown could.
pub fn destroy() -> Result<()> {
    if exists() {
        ip(&["netns", "delete", NETNS])?;
    }
    let _ = fs::remove_file(format!("{NETNS_ETC}/resolv.conf"));
    let _ = fs::remove_dir(NETNS_ETC);
    Ok(())
}

/// Enter the namespace in the *current thread*.
///
/// `setns(2)` moves only the calling thread, and threads created afterwards
/// inherit the namespace. So this must be called before any runtime that might
/// spawn threads is started - which is exactly why tort uses a current-thread
/// tokio runtime and calls this first. Getting this ordering wrong in a
/// language with an implicitly multi-threaded runtime is the class of bug that
/// forced runc to implement namespace entry in C.
pub fn enter() -> Result<()> {
    let path = format!("/var/run/netns/{NETNS}");
    let file = fs::File::open(&path)
        .with_context(|| format!("opening {path} - is tort up?"))?;
    setns(file.as_fd(), CloneFlags::CLONE_NEWNET)
        .context("setns into the tort network namespace")?;
    Ok(())
}
