//! nftables ruleset generation and atomic application.
//!
//! The entire ruleset is generated as text and handed to `nft -f -` in one
//! transaction. This is the property torc's imperative `iptables` calls could
//! not offer: either the whole ruleset applies or none of it does, so there is
//! never a window in which half the rules are live. It also means there is
//! nothing to roll back, because a failed apply changes nothing.
//!
//! Keeping the ruleset as text is a deliberate choice over speaking netlink
//! directly: it can be unit-tested by comparison, printed for a bug report, and
//! pasted into `nft -f` by hand.

use anyhow::{bail, Context, Result};
use std::io::Write;
use std::process::{Command, Stdio};

use crate::config::*;

/// Build the complete ruleset.
///
/// The `add`/`delete`/`table` sequence is the standard atomic-replace idiom:
/// `add` makes the table exist so `delete` cannot fail on a fresh system, and
/// the fresh definition follows - all evaluated as a single transaction.
pub fn ruleset() -> String {
    format!(
        r#"# Generated by tort. Applied atomically via `nft -f`.
add table ip {table}
delete table ip {table}

table ip {table} {{
    # Redirect traffic arriving from the namespace to tort's own tor instance.
    # This runs before the routing decision, so redirected packets are delivered
    # locally to tor rather than being forwarded anywhere.
    chain prerouting {{
        type nat hook prerouting priority dstnat; policy accept;

        iifname "{veth}" udp dport 53 redirect to :{dns}
        iifname "{veth}" meta l4proto tcp redirect to :{trans}
    }}

    # Anything from the namespace that was NOT redirected has no business being
    # forwarded: tor cannot carry it. Dropping it is what makes the design fail
    # closed - UDP (including QUIC on 443), ICMP and every other protocol dies
    # here rather than leaking out the host's default route.
    #
    # The policy is deliberately `accept`, with an explicit drop scoped to our
    # own interface. nftables evaluates the chains of every table registered on
    # a hook, so `policy drop` here would drop forwarded traffic belonging to
    # docker, libvirt, VMs and anything else on the host - a blast radius far
    # beyond tort. Scope the drop, never the policy.
    chain forward {{
        type filter hook forward priority filter; policy accept;

        iifname "{veth}" drop
        oifname "{veth}" drop
    }}

    # Restrict what the namespace may reach on the host itself. Without this the
    # namespace could talk to any service bound on the host side of the veth or
    # on 0.0.0.0, which would be a way around tor.
    chain input {{
        type filter hook input priority filter; policy accept;

        # tor's ports are bound to the veth address so the namespace can reach
        # them - and tor warns, correctly, that this "allows everybody on your
        # local network to use your machine as a proxy". Under Linux's weak host
        # model an address on one interface is reachable via any interface, so a
        # LAN host with a route to this subnet could otherwise use tort as an
        # open proxy. Only the namespace may reach these ports.
        iifname != "{veth}" tcp dport {trans} drop
        iifname != "{veth}" udp dport {dns} drop

        iifname "{veth}" ct state established,related accept
        iifname "{veth}" tcp dport {trans} accept
        iifname "{veth}" udp dport {dns} accept
        iifname "{veth}" drop
    }}
}}
"#,
        table = NFT_TABLE,
        veth = VETH_HOST,
        dns = DNS_PORT,
        trans = TRANS_PORT,
    )
}

/// Apply the ruleset atomically.
pub fn apply() -> Result<()> {
    run_nft(&ruleset()).context("applying the tort nftables ruleset")
}

/// Remove tort's table, leaving every other rule on the system untouched.
///
/// Note what this does *not* do: there is no flush of any built-in chain and no
/// table-wide flush. tort only ever owns `table ip tort`, so removing it cannot
/// disturb the user's firewall, docker, libvirt or anything else.
pub fn remove() -> Result<()> {
    let script = format!("add table ip {t}\ndelete table ip {t}\n", t = NFT_TABLE);
    run_nft(&script).context("removing the tort nftables ruleset")
}

/// Is tort's table currently installed?
pub fn is_installed() -> bool {
    Command::new("nft")
        .args(["list", "table", "ip", NFT_TABLE])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn run_nft(script: &str) -> Result<()> {
    let mut child = Command::new("nft")
        .args(["-f", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .context("could not run `nft` - is nftables installed?")?;

    child
        .stdin
        .take()
        .expect("stdin was piped")
        .write_all(script.as_bytes())
        .context("writing ruleset to nft")?;

    let out = child.wait_with_output().context("waiting for nft")?;
    if !out.status.success() {
        bail!("nft rejected the ruleset: {}", String::from_utf8_lossy(&out.stderr).trim());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ruleset_is_an_atomic_replace() {
        let r = ruleset();
        let add = r.find("add table").expect("add present");
        let del = r.find("delete table").expect("delete present");
        let def = r.find("table ip tort {").expect("definition present");
        // Order matters: add, then delete, then define - all in one file.
        assert!(add < del && del < def, "atomic-replace idiom is out of order");
    }

    #[test]
    fn unredirected_namespace_traffic_is_dropped() {
        // The fail-closed property: anything from the namespace that was not
        // redirected to tor dies at the forward hook instead of leaving.
        let r = ruleset();
        assert!(r.contains(&format!("iifname \"{VETH_HOST}\" drop")));
        assert!(r.contains(&format!("oifname \"{VETH_HOST}\" drop")));
    }

    #[test]
    fn no_chain_sets_a_drop_policy() {
        // nftables runs the chains of every table registered on a hook, so a
        // `policy drop` in tort's table would silently drop traffic belonging
        // to docker, libvirt or any VM on the host. Drops must always be
        // scoped to tort's own interface.
        let rules_only: String = ruleset()
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            !rules_only.contains("policy drop"),
            "a drop policy here would affect traffic that has nothing to do with tort"
        );
    }

    #[test]
    fn tor_ports_are_unreachable_from_outside_the_namespace() {
        let r = ruleset();
        assert!(r.contains(&format!("iifname != \"{VETH_HOST}\" tcp dport {TRANS_PORT} drop")));
        assert!(r.contains(&format!("iifname != \"{VETH_HOST}\" udp dport {DNS_PORT} drop")));
    }

    #[test]
    fn namespace_cannot_reach_arbitrary_host_ports() {
        let r = ruleset();
        assert!(r.contains(&format!("iifname \"{VETH_HOST}\" drop")));
    }

    #[test]
    fn no_builtin_chain_is_ever_flushed() {
        // The bug that made torc destroy unrelated firewall rules.
        let r = ruleset();
        assert!(!r.contains("flush"), "ruleset must not flush anything");
    }
}
