//! tort's own tor instance.
//!
//! tort never edits /etc/tor/torrc and never touches the system tor service.
//! It writes its own config, on its own ports, with its own DataDirectory, and
//! runs its own process. Stopping tort therefore cannot disrupt a tor the user
//! was already running, and starting it needs no consent prompt for modifying
//! a shared system file.

use anyhow::{bail, Context, Result};
use std::fs;
use std::net::TcpStream;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;
use std::time::{Duration, Instant};

use crate::config::*;

/// Generate the torrc.
///
/// `AutomapHostsOnResolve` plus `VirtualAddrNetworkIPv4` is not optional
/// decoration: it is what makes .onion addresses resolvable in transparent
/// mode. Tor hands back a virtual IP from that range, which then routes through
/// TransPort. Without the pair, onion services simply do not work here.
pub fn torrc() -> String {
    // tor itself warns when run as root, and it is right to. If the system has
    // a dedicated tor account, hand the daemon over to it; tort still needs
    // root for setns and nftables, but the long-lived network-facing process
    // does not.
    let user_line = match tor_user() {
        Some(u) => format!("User {u}\n"),
        None => String::new(),
    };

    format!(
        "# Generated by tort. Do not edit; it is rewritten on every `tort up`.\n\
         {user_line}\
         DataDirectory {data}\n\
         PidFile {pid}\n\
         RunAsDaemon 1\n\
         \n\
         # Bound to the host side of the veth so the namespace can reach them.\n\
         TransPort {host}:{trans}\n\
         DNSPort {host}:{dns}\n\
         SocksPort 127.0.0.1:{socks}\n\
         \n\
         # Required for .onion resolution through the transparent proxy.\n\
         AutomapHostsOnResolve 1\n\
         VirtualAddrNetworkIPv4 10.192.0.0/10\n\
         \n\
         # tort carries no IPv6 traffic, so do not build IPv6 exits.\n\
         ClientUseIPv6 0\n",
        user_line = user_line,
        data = DATA_DIR,
        pid = TOR_PID,
        host = HOST_ADDR,
        trans = TRANS_PORT,
        dns = DNS_PORT,
        socks = SOCKS_PORT,
    )
}

/// The unprivileged account to run tor under, if the system has one.
pub fn tor_user() -> Option<String> {
    ["tor", "debian-tor", "_tor"]
        .into_iter()
        .find(|u| nix::unistd::User::from_name(u).ok().flatten().is_some())
        .map(str::to_string)
}

pub fn is_installed() -> bool {
    Command::new("tor")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Is a port accepting connections on the host side of the veth?
pub fn port_open(port: u16) -> bool {
    TcpStream::connect_timeout(
        &format!("{HOST_ADDR}:{port}").parse().expect("valid address"),
        Duration::from_millis(300),
    )
    .is_ok()
}

pub fn is_running() -> bool {
    port_open(TRANS_PORT)
}

/// Recursively set ownership, without ever following a symlink.
///
/// AT_SYMLINK_NOFOLLOW matters: this runs as root over a directory that a less
/// privileged account owns, so a symlink planted inside it must not be able to
/// redirect the chown at something outside the tree.
fn chown_tree(path: &Path, uid: nix::unistd::Uid, gid: nix::unistd::Gid) -> Result<()> {
    use nix::fcntl::AtFlags;
    use nix::unistd::fchownat;

    fchownat(None, path, Some(uid), Some(gid), AtFlags::AT_SYMLINK_NOFOLLOW)
        .with_context(|| format!("chown {}", path.display()))?;

    let meta = fs::symlink_metadata(path)?;
    if meta.is_dir() {
        for entry in fs::read_dir(path)? {
            chown_tree(&entry?.path(), uid, gid)?;
        }
    }
    Ok(())
}

/// Write the config and start tor, waiting until it is actually serving.
pub fn start() -> Result<()> {
    fs::create_dir_all(RUN_DIR).with_context(|| format!("creating {RUN_DIR}"))?;
    fs::create_dir_all(DATA_DIR).with_context(|| format!("creating {DATA_DIR}"))?;
    // Tor refuses to start if its DataDirectory is group- or world-accessible.
    fs::set_permissions(DATA_DIR, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("tightening permissions on {DATA_DIR}"))?;

    // If tor is going to drop to an unprivileged account, it must own its
    // DataDirectory or it will refuse to start.
    if let Some(name) = tor_user() {
        if let Ok(Some(u)) = nix::unistd::User::from_name(&name) {
            // Recursive, not just the top directory. An earlier tort that ran
            // tor as root leaves root-owned subdirectories (keys/, state,
            // cached-*) behind, and tor cannot read them once it drops
            // privileges - which is exactly how this surfaced.
            chown_tree(Path::new(DATA_DIR), u.uid, u.gid)
                .with_context(|| format!("giving {DATA_DIR} to the '{name}' account"))?;
        }
    }

    fs::write(TORRC, torrc()).with_context(|| format!("writing {TORRC}"))?;

    let out = Command::new("tor")
        .args(["-f", TORRC])
        .output()
        .context("could not run `tor` - is it installed?")?;

    if !out.status.success() {
        bail!(
            "tor refused to start: {}",
            String::from_utf8_lossy(&out.stdout)
                .lines()
                .filter(|l| l.contains("[warn]") || l.contains("[err]"))
                .collect::<Vec<_>>()
                .join("; ")
        );
    }

    // RunAsDaemon returns immediately; wait for the ports to actually serve.
    let deadline = Instant::now() + Duration::from_secs(30);
    while Instant::now() < deadline {
        if port_open(TRANS_PORT) && port_open(DNS_PORT) {
            return Ok(());
        }
        std::thread::sleep(Duration::from_millis(250));
    }

    bail!("tor started but its TransPort/DNSPort never began accepting connections")
}

/// Stop the tor instance tort started - and only that one.
pub fn stop() -> Result<()> {
    if !Path::new(TOR_PID).exists() {
        return Ok(());
    }

    let pid: i32 = fs::read_to_string(TOR_PID)
        .context("reading tor pidfile")?
        .trim()
        .parse()
        .context("tor pidfile did not contain a pid")?;

    // SAFETY-adjacent: the pid comes from a pidfile tort itself configured, in
    // a root-only runtime directory. We never kill by name, which would risk
    // taking down a tor the user is running for something else.
    let _ = nix::sys::signal::kill(
        nix::unistd::Pid::from_raw(pid),
        nix::sys::signal::Signal::SIGTERM,
    );

    let deadline = Instant::now() + Duration::from_secs(10);
    while Instant::now() < deadline {
        if !port_open(TRANS_PORT) {
            break;
        }
        std::thread::sleep(Duration::from_millis(200));
    }

    let _ = fs::remove_file(TOR_PID);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn torrc_enables_onion_resolution() {
        let c = torrc();
        assert!(c.contains("AutomapHostsOnResolve 1"));
        assert!(c.contains("VirtualAddrNetworkIPv4"));
    }

    #[test]
    fn socks_port_is_not_exposed_on_the_veth() {
        // Binding SOCKS on the veth address would expose it to anything that
        // can route to 10.66.0.0/24, and it serves no purpose there: prerouting
        // redirects all TCP from the namespace to TransPort before it could
        // reach the SOCKS port anyway.
        assert!(torrc().contains("SocksPort 127.0.0.1:"));
        assert!(!torrc().contains(&format!("SocksPort {HOST_ADDR}")));
    }

    #[test]
    fn torrc_uses_non_default_ports() {
        // Colliding with a system tor on 9050/9040/9053 would make tort's
        // behaviour depend on whatever else is running.
        let c = torrc();
        assert!(!c.contains(":9050"));
        assert!(!c.contains(":9040"));
        assert!(!c.contains(":9053"));
    }

    #[test]
    fn torrc_drops_privileges_when_an_account_exists() {
        // tor warns loudly when run as root, and it is right to. If the system
        // has a tor account, the generated config must hand the daemon to it.
        if tor_user().is_some() {
            assert!(torrc().contains("\nUser "), "torrc should contain a User directive");
        }
    }

    #[test]
    fn torrc_never_points_at_the_system_config() {
        assert!(!torrc().contains("/etc/tor"));
    }
}
