//! tort's own tor instance.
//!
//! tort never edits /etc/tor/torrc and never touches the system tor service.
//! It writes its own config, on its own ports, with its own DataDirectory, and
//! runs its own process. Stopping tort therefore cannot disrupt a tor the user
//! was already running, and starting it needs no consent prompt for modifying
//! a shared system file.

use anyhow::{bail, Context, Result};
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;
use std::time::{Duration, Instant};

use crate::config::*;

/// Generate the torrc.
///
/// `AutomapHostsOnResolve` plus `VirtualAddrNetworkIPv4` is not optional
/// decoration: it is what makes .onion addresses resolvable in transparent
/// mode. Tor hands back a virtual IP from that range, which then routes through
/// TransPort. Without the pair, onion services simply do not work here.
pub fn torrc() -> String {
    // tor itself warns when run as root, and it is right to. If the system has
    // a dedicated tor account, hand the daemon over to it; tort still needs
    // root for setns and nftables, but the long-lived network-facing process
    // does not.
    let user_line = match tor_user() {
        Some(u) => format!("User {u}\n"),
        None => String::new(),
    };

    format!(
        "# Generated by tort. Do not edit; it is rewritten on every `tort up`.\n\
         {user_line}\
         DataDirectory {data}\n\
         PidFile {pid}\n\
         RunAsDaemon 1\n\
         Log notice file {log}\n\
         \n\
         # Bound to the host side of the veth so the namespace can reach them.\n\
         TransPort {host}:{trans}\n\
         DNSPort {host}:{dns}\n\
         SocksPort 127.0.0.1:{socks}\n\
         \n\
         # Required for .onion resolution through the transparent proxy.\n\
         AutomapHostsOnResolve 1\n\
         VirtualAddrNetworkIPv4 10.192.0.0/10\n\
         \n\
         # tort carries no IPv6 traffic, so do not build IPv6 exits.\n\
         ClientUseIPv6 0\n",
        user_line = user_line,
        data = DATA_DIR,
        pid = TOR_PID,
        log = TOR_LOG,
        host = HOST_ADDR,
        trans = TRANS_PORT,
        dns = DNS_PORT,
        socks = SOCKS_PORT,
    )
}

/// The unprivileged account to run tor under, if the system has one.
pub fn tor_user() -> Option<String> {
    ["tor", "debian-tor", "_tor"]
        .into_iter()
        .find(|u| nix::unistd::User::from_name(u).ok().flatten().is_some())
        .map(str::to_string)
}

pub fn is_installed() -> bool {
    Command::new("tor")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Is tort's tor instance running?
///
/// Determined from the process list rather than by connecting to TransPort.
/// Probing that port is not free: tor accepts the connection, asks the kernel
/// for the original destination via SO_ORIGINAL_DST, gets the veth address
/// because nothing NAT-redirected it, and logs "Rejecting request for anonymous
/// connection to private address ... Possible loop in your NAT rules?". That
/// warning is entirely self-inflicted and sent several debugging sessions in
/// the wrong direction.
pub fn is_running() -> bool {
    !our_tor_processes().is_empty()
}

/// Recursively set ownership, without ever following a symlink.
///
/// AT_SYMLINK_NOFOLLOW matters: this runs as root over a directory that a less
/// privileged account owns, so a symlink planted inside it must not be able to
/// redirect the chown at something outside the tree.
fn chown_tree(path: &Path, uid: nix::unistd::Uid, gid: nix::unistd::Gid) -> Result<()> {
    use nix::fcntl::AtFlags;
    use nix::unistd::fchownat;

    fchownat(None, path, Some(uid), Some(gid), AtFlags::AT_SYMLINK_NOFOLLOW)
        .with_context(|| format!("chown {}", path.display()))?;

    let meta = fs::symlink_metadata(path)?;
    if meta.is_dir() {
        for entry in fs::read_dir(path)? {
            chown_tree(&entry?.path(), uid, gid)?;
        }
    }
    Ok(())
}

/// Write the config and start tor, waiting until it is actually serving.
pub fn start() -> Result<()> {
    // Clear any orphan from an earlier run before binding the same ports.
    let orphans = our_tor_processes();
    if !orphans.is_empty() {
        eprintln!("  cleaning up {} orphaned tor process(es) from a previous run", orphans.len());
        stop()?;
    }

    fs::create_dir_all(RUN_DIR).with_context(|| format!("creating {RUN_DIR}"))?;
    fs::create_dir_all(DATA_DIR).with_context(|| format!("creating {DATA_DIR}"))?;

    // tor drops to an unprivileged account and only then opens its log, so the
    // runtime directory must belong to that account or the open fails with
    // EACCES. Both directories are 0700: the log and the tor state describe the
    // user's network activity and are nobody else's business.
    fs::set_permissions(RUN_DIR, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("tightening permissions on {RUN_DIR}"))?;
    // Tor refuses to start if its DataDirectory is group- or world-accessible.
    fs::set_permissions(DATA_DIR, fs::Permissions::from_mode(0o700))
        .with_context(|| format!("tightening permissions on {DATA_DIR}"))?;

    fs::write(TORRC, torrc()).with_context(|| format!("writing {TORRC}"))?;

    // Remove the previous run's log first. Bootstrap detection reads this file,
    // and a stale "Bootstrapped 100%" from an earlier run would be taken as
    // this run's success.
    let _ = fs::remove_file(TOR_LOG);

    // Ownership is applied last so it covers everything just written, including
    // the config itself and anything a previous run left behind.
    if let Some(name) = tor_user() {
        if let Ok(Some(u)) = nix::unistd::User::from_name(&name) {
            // The runtime directory, so tor can create its own log and pidfile
            // there after dropping privileges.
            chown_tree(Path::new(RUN_DIR), u.uid, u.gid)
                .with_context(|| format!("giving {RUN_DIR} to the '{name}' account"))?;
            // Recursive, not just the top directory. An earlier tort that ran
            // tor as root leaves root-owned subdirectories (keys/, state,
            // cached-*) behind, and tor cannot read them once it drops
            // privileges - which is exactly how this surfaced.
            chown_tree(Path::new(DATA_DIR), u.uid, u.gid)
                .with_context(|| format!("giving {DATA_DIR} to the '{name}' account"))?;
        }
    }

    let out = Command::new("tor")
        .args(["-f", TORRC])
        .output()
        .context("could not run `tor` - is it installed?")?;

    if !out.status.success() {
        bail!(
            "tor refused to start: {}",
            String::from_utf8_lossy(&out.stdout)
                .lines()
                .filter(|l| l.contains("[warn]") || l.contains("[err]"))
                .collect::<Vec<_>>()
                .join("; ")
        );
    }

    // RunAsDaemon means the process we just ran forked and exited, so its exit
    // status says nothing about whether the daemon survived. Readiness is taken
    // from tor's own log rather than by probing TransPort: binding a port is
    // not readiness (tor cannot carry traffic until it has a consensus and
    // circuits), and probing it makes tor log a spurious NAT-loop warning.
    if is_running() {
        return wait_for_bootstrap(Duration::from_secs(120));
    }

    bail!(
        "tor exited immediately after starting.\nLast lines of {TOR_LOG}:\n{}",
        log_tail()
    )
}

/// Wait until tor reports a fully bootstrapped connection to the network.
///
/// Progress is echoed as it changes, because this legitimately takes tens of
/// seconds and silence is indistinguishable from a hang.
pub fn wait_for_bootstrap(timeout: Duration) -> Result<()> {
    let deadline = Instant::now() + timeout;
    let mut last_shown = String::new();

    loop {
        if let Ok(text) = fs::read_to_string(TOR_LOG) {
            if text.contains("Bootstrapped 100%") {
                println!("  tor bootstrapped");
                return Ok(());
            }

            // Fail fast on a fatal error rather than waiting out the timeout.
            if let Some(line) = text.lines().rev().find(|l| l.contains("[err]")) {
                bail!("tor reported a fatal error while bootstrapping:\n  {}", line.trim());
            }

            if let Some(line) = text.lines().rev().find(|l| l.contains("Bootstrapped ")) {
                let progress = line
                    .split_once("Bootstrapped ")
                    .map(|(_, rest)| rest.trim())
                    .unwrap_or_default()
                    .to_string();
                if progress != last_shown {
                    println!("  tor: {progress}");
                    last_shown = progress;
                }
            }
        }

        // A daemon that has died will never make progress, so stop waiting on
        // it. Without this the wait burns its whole budget and then reports a
        // timeout, which describes the symptom rather than the cause.
        if !is_running() {
            bail!(
                "the tor daemon exited while bootstrapping.\nLast lines of {TOR_LOG}:\n{}",
                log_tail()
            );
        }

        if Instant::now() >= deadline {
            bail!(
                "tor did not finish bootstrapping within {}s (reached {}).\n\
                 Last lines of {TOR_LOG}:\n{}",
                timeout.as_secs(),
                if last_shown.is_empty() { "no progress at all" } else { &last_shown },
                log_tail()
            );
        }
        std::thread::sleep(Duration::from_millis(500));
    }
}

/// The last few lines of tor's log, for when the daemon dies after forking.
fn log_tail() -> String {
    match fs::read_to_string(TOR_LOG) {
        Ok(text) => {
            // Drop raw stack frames. When tor crashes it prints a long
            // backtrace, which pushes the actual error message out of view -
            // the address lines are useless without tor's debug symbols anyway.
            let lines: Vec<&str> = text
                .lines()
                .filter(|l| !l.trim_start().starts_with("tor(+0x"))
                .filter(|l| !l.contains(".so") || l.contains("["))
                .filter(|l| !l.trim_start().starts_with("/usr/lib/"))
                .collect();
            let start = lines.len().saturating_sub(15);
            lines[start..].join("\n")
        }
        Err(e) => format!("(could not read {TOR_LOG}: {e})"),
    }
}

/// Every running process whose command line references tort's own torrc.
///
/// This is how orphans are found. Matching on the config path is precise: it
/// cannot match the user's system tor, or any other tor instance, because only
/// tort ever passes this file. Matching on the process *name* would be
/// unacceptable - it would kill unrelated tor daemons.
pub fn our_tor_processes() -> Vec<i32> {
    let mut pids = Vec::new();
    let Ok(entries) = fs::read_dir("/proc") else {
        return pids;
    };

    for entry in entries.flatten() {
        let name = entry.file_name();
        let Some(pid) = name.to_str().and_then(|n| n.parse::<i32>().ok()) else {
            continue;
        };
        if let Ok(cmdline) = fs::read(entry.path().join("cmdline")) {
            // /proc cmdline is NUL-separated.
            let cmdline = String::from_utf8_lossy(&cmdline).replace('\0', " ");
            if cmdline.contains(TORRC) {
                pids.push(pid);
            }
        }
    }
    pids
}

/// Stop the tor instance tort started - and only that one.
///
/// The pidfile alone is not enough. tor daemonises, so a `tort up` that failed
/// *after* tor forked (a bootstrap timeout, say) left the daemon running with
/// nothing tracking it; the next run then found its port already bound and
/// behaved incomprehensibly. Orphans are now found by scanning /proc for
/// processes started with tort's own torrc.
pub fn stop() -> Result<()> {
    let mut pids = our_tor_processes();

    // The pidfile as well, in case the process list missed it.
    if let Ok(text) = fs::read_to_string(TOR_PID) {
        if let Ok(pid) = text.trim().parse::<i32>() {
            if !pids.contains(&pid) {
                pids.push(pid);
            }
        }
    }

    if pids.is_empty() {
        let _ = fs::remove_file(TOR_PID);
        return Ok(());
    }

    for pid in &pids {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(*pid),
            nix::sys::signal::Signal::SIGTERM,
        );
    }

    let deadline = Instant::now() + Duration::from_secs(10);
    while Instant::now() < deadline {
        if our_tor_processes().is_empty() {
            break;
        }
        std::thread::sleep(Duration::from_millis(200));
    }

    // Anything still alive after a polite SIGTERM gets SIGKILL, so a wedged tor
    // cannot block the next run.
    for pid in our_tor_processes() {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(pid),
            nix::sys::signal::Signal::SIGKILL,
        );
    }

    let _ = fs::remove_file(TOR_PID);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn torrc_enables_onion_resolution() {
        let c = torrc();
        assert!(c.contains("AutomapHostsOnResolve 1"));
        assert!(c.contains("VirtualAddrNetworkIPv4"));
    }

    #[test]
    fn tor_logs_to_a_file() {
        // Without this, a tor that dies after daemonising leaves no explanation.
        assert!(torrc().contains("Log notice file"));
    }

    #[test]
    fn socks_port_is_not_exposed_on_the_veth() {
        // Binding SOCKS on the veth address would expose it to anything that
        // can route to 10.66.0.0/24, and it serves no purpose there: prerouting
        // redirects all TCP from the namespace to TransPort before it could
        // reach the SOCKS port anyway.
        assert!(torrc().contains("SocksPort 127.0.0.1:"));
        assert!(!torrc().contains(&format!("SocksPort {HOST_ADDR}")));
    }

    #[test]
    fn torrc_uses_non_default_ports() {
        // Colliding with a system tor on 9050/9040/9053 would make tort's
        // behaviour depend on whatever else is running.
        let c = torrc();
        assert!(!c.contains(":9050"));
        assert!(!c.contains(":9040"));
        assert!(!c.contains(":9053"));
    }

    #[test]
    fn torrc_drops_privileges_when_an_account_exists() {
        // tor warns loudly when run as root, and it is right to. If the system
        // has a tor account, the generated config must hand the daemon to it.
        if tor_user().is_some() {
            assert!(torrc().contains("\nUser "), "torrc should contain a User directive");
        }
    }

    #[test]
    fn torrc_never_points_at_the_system_config() {
        assert!(!torrc().contains("/etc/tor"));
    }
}
